### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by trasherdk** [monero-ecosystem/monero-javascript#11]
Is there a recipe to build from source.
The description in README.md is not working.
`export EMSCRIPTEN=<emsdk_root>/fastcomp/emscripten` directory does not exist.
Running `./bin/build-emcpp.sh` failing with:
```
fatal error: 'openssl/conf.h' file not found
     #include <openssl/conf.h>
              ^~~~~~~~~~~~~~~~
```

**Comment by woodser** [comment]
`EMSCRIPTEN` must be set to the absolute path of the emcripten project on your system.

I updated the instructions to read: `export EMSCRIPTEN=/absolute/path/to/emsdk/fastcomp/emscripten` (set for your system)

If you are building the experimental core wallet, use these [updated instructions](https://github.com/monero-ecosystem/monero-javascript/blob/wasm110_proxy_to_worker_merge/README.md#how-to-build-webassembly-files-from-source) which download and build OpenSSL.

**Comment by trasherdk** [comment]
I'm still trying to figure out `Digest Authentication`, using the recommended `wasm83_start_syncing` branch.

No `fastcomp` directory in `/path/to/build-emscripten/emsdk/`
There is a `fastcomp` directory in `/path/to/build-emscripten/emsdk/upstream/`
No `emscripten` directory in `/path/to/build-emscripten/emsdk/upstream/fastcomp/`
The `build-boost-emscripten.sh` script is looking for `embuilder.py` which is located in
`/path/to/build-emscripten/emsdk/upstream/emscripten/`
when running `$ ./emsdk activate latest` I get:
```
NODE_JS = '/path/to/build-emscripten/emsdk/node/12.9.1_64bit/bin/node'
LLVM_ROOT = '/path/to/build-emscripten/emsdk/upstream/bin'
BINARYEN_ROOT = '/path/to/build-emscripten/emsdk/upstream'
EMSCRIPTEN_ROOT = '/path/to/build-emscripten/emsdk/upstream/emscripten'
TEMP_DIR = '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```
Followed by:
```
$ source ./emsdk_env.sh
Adding directories to PATH:
PATH += /home/crypto/local/build/build-emscripten/emsdk
PATH += /home/crypto/local/build/build-emscripten/emsdk/upstream/emscripten
PATH += /home/crypto/local/build/build-emscripten/emsdk/node/12.9.1_64bit/bin

Setting environment variables:
EMSDK = /home/crypto/local/build/build-emscripten/emsdk
EM_CONFIG = /home/crypto/.emscripten
EMSDK_NODE = /home/crypto/local/build/build-emscripten/emsdk/node/12.9.1_64bit/bin/node
```

**Comment by woodser** [comment]
I updated the [instructions](https://github.com/monero-ecosystem/monero-javascript/blob/wasm110_proxy_to_worker_merge/README.md#how-to-build-webassembly-files-from-source) to use `/absolute/path/to/emsdk/upstream/emscripten` (I must have been moving things around locally).

I also updated the instructions to use latest-upstream which has resolved issues for others.

**Comment by trasherdk** [comment]
Still no go..
Building `monero-core` yields:
```
[ 86%] Linking CXX executable ../../bin/monero-gen-ssl-cert
/usr/lib64/gcc/x86_64-slackware-linux/5.5.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.5.0/../../../../lib64/libtermcap.a(termcap.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.5.0/../../../../lib64/libtermcap.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/gen_ssl_cert/CMakeFiles/gen_ssl_cert.dir/build.make:119: recipe for target 'bin/monero-gen-ssl-cert' failed
make[3]: *** [bin/monero-gen-ssl-cert] Error 1
make[3]: Leaving directory '/home/crypto/local/build/build-xmr-sample-app/woodser/monero-javascript/external/monero-cpp-library/external/monero-core/build/release'
CMakeFiles/Makefile2:3424: recipe for target 'src/gen_ssl_cert/CMakeFiles/gen_ssl_cert.dir/all' failed
make[2]: *** [src/gen_ssl_cert/CMakeFiles/gen_ssl_cert.dir/all] Error 2
```

```
$ ./bin/build-openssl-emscripten.sh 
Traceback (most recent call last):
  File "/home/crypto/local/build/build-emscripten/emsdk/upstream/emscripten/emconfigure.py", line 61, in <module>
    sys.exit(run())
  File "/home/crypto/local/build/build-emscripten/emsdk/upstream/emscripten/emconfigure.py", line 54, in run
    shared.Building.configure(sys.argv[1:])
  File "/home/crypto/local/build/build-emscripten/emsdk/upstream/emscripten/tools/shared.py", line 1746, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File "/home/crypto/local/build/build-emscripten/emsdk/upstream/emscripten/tools/shared.py", line 188, in run_process
    proc = Popen(cmd, *args, **kw)
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
ERROR: OpenSSL Configure FAILED!
```
Running, in `openssl-sdk`, the `./Configure --bla --bla` by hand succeeds.
```
# set define_atomics
to_defined_atomics_line='\&\& !defined(__STDC_NO_ATOMICS__) \&\& !defined(__EMSCRIPTEN__)'
sed -i.bak 's/\&\&\ !defined(__STDC_NO_ATOMICS__)$/'"$to_defined_atomics_line"'/' include/internal/refcount.h #the pattern is relying here on the fact the "ATOMICS__)" comes at the end of the line
```
`include/internal/refcount.h` does not exist.

Running `build-openssl-emscripten.sh`by hand seems to work. I got `build/openssl` installed.

But `./bin/build-emcpp.sh` complains a lot before dying.
```
$ ./bin/build-emcpp.sh
-- EMCC_LINKER_FLAGS__WASM -Wall -std=c++11 --bind -s MODULARIZE=1 -Oz -s 'EXPORT_NAME="monero_javascript"' --llvm-lto 1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s ASSERTIONS=2 -s EXIT_RUNTIME=0 -s ASYNCIFY=1 -s 'ASYNCIFY_IMPORTS=["js_send_json_request","js_send_binary_request","emscripten_sleep"]' -s PRECISE_F32=1 -s EXCEPTION_DEBUG=1 -s DEMANGLE_SUPPORT=1 -s NO_DYNAMIC_EXECUTION=1 -s NODEJS_CATCH_EXIT=0 -s RESERVED_FUNCTION_POINTERS=5 -s EXTRA_EXPORTED_RUNTIME_METHODS='["UTF8ToString","stringToUTF8","lengthBytesUTF8","intArrayToString","makeBigInt","getTempRet0","addFunction"]'  -s WASM=1 -s ALLOW_MEMORY_GROWTH=0 -s TOTAL_MEMORY=512MB --post-js /path/to/monero-javascript/src/main/js/module-post.js 
-- EMCC_LINKER_FLAGS__ASMJS -Wall -std=c++11 --bind -s MODULARIZE=1 -Oz -s 'EXPORT_NAME="monero_javascript"' --llvm-lto 1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s ASSERTIONS=2 -s EXIT_RUNTIME=0 -s ASYNCIFY=1 -s 'ASYNCIFY_IMPORTS=["js_send_json_request","js_send_binary_request","emscripten_sleep"]' -s PRECISE_F32=1 -s EXCEPTION_DEBUG=1 -s DEMANGLE_SUPPORT=1 -s NO_DYNAMIC_EXECUTION=1 -s NODEJS_CATCH_EXIT=0 -s RESERVED_FUNCTION_POINTERS=5 -s EXTRA_EXPORTED_RUNTIME_METHODS='["UTF8ToString","stringToUTF8","lengthBytesUTF8","intArrayToString","makeBigInt","getTempRet0","addFunction"]'  -s WASM=0 -Os --separate-asm -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s ALLOW_MEMORY_GROWTH=1 --memory-init-file 0 
-- Configuring done
-- Generating done
-- Build files have been written to: /path/to/monero-javascript/build
make: ['cmake', '--build', '.']
Scanning dependencies of target monero-javascript-wasm
[  1%] Building CXX object CMakeFiles/monero-javascript-wasm.dir/src/main/cpp/index.cpp.o
[  3%] Building CXX object CMakeFiles/monero-javascript-wasm.dir/src/main/cpp/monero_wasm_bridge.cpp.o
/path/to/monero-javascript/src/main/cpp/monero_wasm_bridge.cpp:128:128: error: too many arguments to function call, expected 3, have 6
  monero_wallet* wallet = monero_wallet_core::open_wallet(password, static_cast<monero_network_type>(network_type), keys_data, cache_data, daemon_connection, make_shared<http_client_wasm>());
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/monero-javascript/external/monero-cpp-library/src/wallet/monero_wallet_core.h:100:5: note: 'open_wallet' declared here
    static monero_wallet_core* open_wallet(const string& path, const string& password, const monero_network_type network_type);
    ^
/path/to/monero-javascript/src/main/cpp/monero_wasm_bridge.cpp:134:159: error: too many arguments to function call, expected at most 5, have 6
  monero_wallet* wallet = monero_wallet_core::create_wallet_random("", password, static_cast<monero_network_type>(network_type), daemon_connection, language, make_shared<http_client_wasm>());
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/monero-javascript/external/monero-cpp-library/src/wallet/monero_wallet_core.h:111:5: note: 'create_wallet_random' declared here
    static monero_wallet_core* create_wallet_random(const string& path, const string& password, const monero_network_type network_type, const monero_rpc_connection& daemon_connection, const string& language = "English");
    ^
/path/to/monero-javascript/src/main/cpp/monero_wasm_bridge.cpp:140:195: error: too many arguments to function call, expected 7, have 8
  monero_wallet* wallet = monero_wallet_core::create_wallet_from_mnemonic("", password, static_cast<monero_network_type>(network_type), mnemonic, daemon_connection, restore_height, seed_offset, make_shared<http_client_wasm>());
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/monero-javascript/external/monero-cpp-library/src/wallet/monero_wallet_core.h:124:5: note: 'create_wallet_from_mnemonic' declared here
    static monero_wallet_core* create_wallet_from_mnemonic(const string& path, const string& password, const monero_network_type network_type, const string& mnemonic, const monero_rpc_connection& daemon_connection, uint64_t restore_height, const string& seed_offset);
    ^
/path/to/monero-javascript/src/main/cpp/monero_wasm_bridge.cpp:146:208: error: too many arguments to function call, expected 9, have 10
  monero_wallet* wallet = monero_wallet_core::create_wallet_from_keys("", password, static_cast<monero_network_type>(network_type), address, view_key, spend_key, daemon_connection, restore_height, language, make_shared<http_client_wasm>());
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/monero-javascript/external/monero-cpp-library/src/wallet/monero_wallet_core.h:139:5: note: 'create_wallet_from_keys' declared here
    static monero_wallet_core* create_wallet_from_keys(const string& path, const string& password, const monero_network_type network_type, const string& address, const string& view_key, const string& spend_key, const monero_rpc_connection& daemon_connection, uint64_t restore_height, const string& language);
    ^
/path/to/monero-javascript/src/main/cpp/monero_wasm_bridge.cpp:189:42: error: no viable conversion from 'shared_ptr<monero::monero_rpc_connection>' to 'boost::optional<monero_rpc_connection>'
  boost::optional<monero_rpc_connection> daemon_connection = wallet->get_daemon_connection();
                                         ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/monero-javascript/build/boost/include/boost/optional/optional.hpp:871:5: note: candidate constructor not viable: no known conversion from 'shared_ptr<monero::monero_rpc_connection>' to 'boost::none_t' for 1st argument
    optional( none_t none_ ) BOOST_NOEXCEPT : base(none_) {}
    ^
/path/to/monero-javascript/build/boost/include/boost/optional/optional.hpp:875:5: note: candidate constructor not viable: no known conversion from 'shared_ptr<monero::monero_rpc_connection>' to 'boost::optional<monero::monero_rpc_connection>::argument_type' (aka 'const monero::monero_rpc_connection &') for 1st argument
    optional ( argument_type val ) : base(optional_detail::init_value_tag(), val) {}
    ^
/path/to/monero-javascript/build/boost/include/boost/optional/optional.hpp:880:5: note: candidate constructor not viable: no known conversion from 'shared_ptr<monero::monero_rpc_connection>' to 'boost::optional<monero::monero_rpc_connection>::rval_reference_type' (aka 'monero::monero_rpc_connection &&') for 1st argument
    optional ( rval_reference_type val ) : base(optional_detail::init_value_tag(), boost::forward<T>(val))
    ^
/path/to/monero-javascript/build/boost/include/boost/optional/optional.hpp:960:5: note: candidate constructor not viable: no known conversion from 'shared_ptr<monero::monero_rpc_connection>' to 'const boost::optional<monero::monero_rpc_connection> &' for 1st argument
    optional ( optional const& ) = default;
    ^
/path/to/monero-javascript/build/boost/include/boost/optional/optional.hpp:970:5: note: candidate constructor not viable: no known conversion from 'shared_ptr<monero::monero_rpc_connection>' to 'boost::optional<monero::monero_rpc_connection> &&' for 1st argument
    optional ( optional && rhs ) = default;
    ^
/path/to/monero-javascript/build/boost/include/boost/optional/optional.hpp:901:14: note: explicit constructor is not a candidate
    explicit optional ( optional<U> const& rhs
             ^
/path/to/monero-javascript/build/boost/include/boost/optional/optional.hpp:918:14: note: explicit constructor is not a candidate
    explicit optional ( optional<U> && rhs
             ^
/path/to/monero-javascript/build/boost/include/boost/optional/optional.hpp:945:12: note: explicit constructor is not a candidate
  explicit optional ( Expr&& expr,
           ^
/path/to/monero-javascript/build/boost/include/boost/optional/optional.hpp:1110:14: note: explicit constructor is not a candidate
    explicit optional ( in_place_init_t, Args&&... args )
             ^
/path/to/monero-javascript/src/main/cpp/monero_wasm_bridge.cpp:676:29: error: no member named 'get_keys_file_buffer' in 'monero::monero_wallet_core'
  string keys_buf = wallet->get_keys_file_buffer(password, watch_only);
                    ~~~~~~  ^
/path/to/monero-javascript/src/main/cpp/monero_wasm_bridge.cpp:696:30: error: no member named 'get_cache_file_buffer' in 'monero::monero_wallet_core'
  string cache_buf = wallet->get_cache_file_buffer(password);
                     ~~~~~~  ^
In file included from /path/to/monero-javascript/src/main/cpp/monero_wasm_bridge.cpp:3:
In file included from /path/to/monero-javascript/external/monero-cpp-library/src/wallet/monero_wallet_keys.h:56:
In file included from /path/to/monero-javascript/external/monero-cpp-library/external/monero-core/src/cryptonote_basic/account.h:33:
In file included from /path/to/monero-javascript/external/monero-cpp-library/external/monero-core/src/cryptonote_basic/cryptonote_basic.h:41:
/path/to/monero-javascript/external/monero-cpp-library/external/monero-core/src/serialization/binary_archive.h:195:28: warning: shift count >= width of type [-Wshift-count-overflow]
      if (1 < sizeof(T)) v >>= 8;
                           ^   ~
/path/to/monero-javascript/external/monero-cpp-library/external/monero-core/src/serialization/binary_archive.h:188:5: note: in instantiation of function template specialization 'binary_archive<true>::serialize_uint<unsigned char>' requested here
    serialize_uint(static_cast<typename boost::make_unsigned<T>::type>(v));
    ^
/path/to/monero-javascript/external/monero-cpp-library/external/monero-core/src/serialization/binary_archive.h:228:5: note: in instantiation of function template specialization 'binary_archive<true>::serialize_int<unsigned char>' requested here
    serialize_int(t);
    ^
1 warning and 7 errors generated.
```

**Comment by woodser** [comment]
Building `monero-core` does not need to finish for the translations directory to build.

For `./bin/build-emcpp.sh`, can you check out monero-cpp-library branch `wasm76_merge_sign_txs` if you are not using that already?

**Comment by trasherdk** [comment]
Okay. A bit closer, but still no cigar.

`monero-javascript` branch `wasm110_proxy_to_worker_merge`
`monero-cpp-library` branch `wasm76_merge_sign_txs`
`monero-core` branch `branch wasm68_onward`

Running `$ ./bin/build-emcpp.sh` ends with:
```
[ 98%] Linking CXX executable monero-javascript-wasm.js
cache:INFO: generating system library: libc++-noexcept.a... (this will be cached in "$HOME/.emscripten_cache/wasm-obj/libc++-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++abi-noexcept.a... (this will be cached in "$HOME/.emscripten_cache/wasm-obj/libc++abi-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libembind-rtti.a... (this will be cached in "$HOME/.emscripten_cache/wasm-obj/libembind-rtti.a" for subsequent builds)
cache:INFO:  - ok
wasm-ld: error: 'atomics' feature is used by thread.o, so --shared-memory must be used
wasm-ld: error: Target feature 'atomics' used in thread.o is disallowed by CMakeFiles/monero-javascript-wasm.dir/src/main/cpp/monero_wasm_bridge.cpp.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in once.o is disallowed by CMakeFiles/monero-javascript-wasm.dir/src/main/cpp/monero_wasm_bridge.cpp.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in future.o is disallowed by CMakeFiles/monero-javascript-wasm.dir/src/main/cpp/monero_wasm_bridge.cpp.o. Use --no-check-features to suppress.
shared:ERROR: '/path/to/emsdk/upstream/bin/wasm-ld @/tmp/emscripten_jgva_c.rsp' failed (1)
CMakeFiles/monero-javascript-wasm.dir/build.make:1803: recipe for target 'monero-javascript-wasm.js' failed
gmake[2]: *** [monero-javascript-wasm.js] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/monero-javascript-wasm.dir/all' failed
gmake[1]: *** [CMakeFiles/monero-javascript-wasm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
gmake: *** [all] Error 2
```

**Comment by woodser** [comment]
I ran into the same error when libraries are built with mismatching threading.  The error goes away when all libraries are built either single or multi threaded.

The project build scripts all use single threaded suggesting your build is pulling libraries from elsewhere.  First thing I would try is to restore your boost-sdk and openssl-sdk directories in ./external/monero-cpp-library/external to their freshly downloaded state (you mentioned building those independently).

**Comment by trasherdk** [comment]
The boost-sdk builds using the `build-boost-emscripten.sh`
The openss-sdk fails using the `build-openssl-emscripten.sh`

```
$ ./bin/build-openssl-emscripten.sh 
Traceback (most recent call last):
  File "/home/crypto/local/build/build-emscripten/emsdk/upstream/emscripten/emconfigure.py", line 61, in <module>
    sys.exit(run())
  File "/home/crypto/local/build/build-emscripten/emsdk/upstream/emscripten/emconfigure.py", line 54, in run
    shared.Building.configure(sys.argv[1:])
  File "/home/crypto/local/build/build-emscripten/emsdk/upstream/emscripten/tools/shared.py", line 1746, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File "/home/crypto/local/build/build-emscripten/emsdk/upstream/emscripten/tools/shared.py", line 188, in run_process
    proc = Popen(cmd, *args, **kw)
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
ERROR: OpenSSL Configure FAILED!
```

**Comment by woodser** [comment]
The openssl build script came from MyMonero.  We're both able to run it suggesting something with your local setup.

You might try clearing any local cache (e.g. rm -rf ~/.emscripten, rm -rf ~/.emscripten_cache, delete the build directory of monero-javascript and its submodules) then re-running the build scripts with the unbuilt openssl-sdk directory.

**Comment by trasherdk** [comment]
The `./bin/build-openssl-emscripten.sh` tries to execute `openssl-sdk/Configure` which is a perl script.

The usual way to build openssl, is to run the `config` script, which in turn run the `Configure` script.

I'm not sure, but building 32bit stuff on a 64bit system sounds unhealthy.

**Comment by woodser** [comment]
Unrelated, I created a branch, `master_core_wallet`, in each project (`xmr-sample-app`, `monero-javascript`, `monero-cpp-library`, and `monero-core`) for the latest stable pre-release of the core wallet which I will keep updated.  I recently pushed updates to those branches supporting configuration to proxy the daemon and wallet to a worker.

**Comment by trasherdk** [comment]
You might wanna mention `openssl-1.1.1` is required. `Slackware 14.2` is on `openssl-1.0.2`.
Is there any other libraries that needs to be at specific versions?

Changing `build-openssl-emscripten.sh`
From `emconfigure ./Configure \` to `emconfigure perl ./Configure \` make it run without serious problems.

Getting same error as before. Seems like I'm missing a `--shared-memory` flag somewhere.

Running `./bin/build-emcpp.sh` ends with:
```
[100%] Linking CXX executable monero-javascript-wasm.js
cache:INFO: generating system library: libc++-noexcept.a... (this will be cached in "~/.emscripten_cache/wasm-obj/libc++-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++abi-noexcept.a... (this will be cached in "~/.emscripten_cache/wasm-obj/libc++abi-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libembind-rtti.a... (this will be cached in "~/.emscripten_cache/wasm-obj/libembind-rtti.a" for subsequent builds)
cache:INFO:  - ok
wasm-ld: error: 'atomics' feature is used by thread.o, so --shared-memory must be used
wasm-ld: error: Target feature 'atomics' used in thread.o is disallowed by CMakeFiles/monero-javascript-wasm.dir/src/main/cpp/monero_wasm_bridge.cpp.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in once.o is disallowed by CMakeFiles/monero-javascript-wasm.dir/src/main/cpp/monero_wasm_bridge.cpp.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in future.o is disallowed by CMakeFiles/monero-javascript-wasm.dir/src/main/cpp/monero_wasm_bridge.cpp.o. Use --no-check-features to suppress.
shared:ERROR: '/path/to/emsdk/upstream/bin/wasm-ld @/tmp/emscripten_2PFcPQ.rsp' failed (1)
CMakeFiles/monero-javascript-wasm.dir/build.make:1803: recipe for target 'monero-javascript-wasm.js' failed
gmake[2]: *** [monero-javascript-wasm.js] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/monero-javascript-wasm.dir/all' failed
gmake[1]: *** [CMakeFiles/monero-javascript-wasm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
gmake: *** [all] Error 2
```

**Comment by woodser** [comment]
I toiled with this same error and the only resolution was to ensure all libraries were using the same threading.  I found the build would pull dependencies from my system which had different threading.  Assuming openssl-sdk and boost-sdk directories are unbuilt and you are building into a fresh `build` directory so nothing is cached, you can check when building boost, openssl, and `./bin/build-emcpp.sh`, that nothing on the console indicates using pthreads.  I recall OpenSSL defaulting to using pthreads which the script should override.

**Comment by trasherdk** [comment]
Boost is build with thread.
```
./bootstrap.sh \
  --with-libraries=system,thread,chrono,serialization,regex \
2>&1
```
In the start of boost build:
```
 (in-process)
 "/path/to/emsdk/upstream/bin/clang-11"
	-cc1
	-triple wasm32-unknown-emscripten
	-emit-obj
	-disable-free
	-main-file-name thread_clock.cpp
	-mrelocation-model static
	-mthread-model posix   <----- Looks like pthread to me ???
	-mframe-pointer=none
	-fno-rounding-math
	-masm-verbose
```

**Comment by trasherdk** [comment]
It does look like boost is build with pthread
```
shared:INFO: (Emscripten: Running sanity checks)
 "/path/to/emsdk/upstream/bin/clang++"
	-target wasm32-unknown-emscripten
	-D__EMSCRIPTEN_major__=1
	-D__EMSCRIPTEN_minor__=39
	-D__EMSCRIPTEN_tiny__=7
	-D_LIBCPP_ABI_VERSION=2
	-Dunix
	-D__unix
	-D__unix__
	-Werror=implicit-function-declaration
	-Xclang
	-nostdsysteminc
	-Xclang
	-isystem/path/to/emsdk/upstream/emscripten/system/include/libcxx
	-Xclang
	-isystem/path/to/emsdk/upstream/emscripten/system/lib/libcxxabi/include
	-Xclang
	-isystem/path/to/emsdk/upstream/emscripten/system/include/compat
	-Xclang
	-isystem/path/to/emsdk/upstream/emscripten/system/include
	-Xclang
	-isystem/path/to/emsdk/upstream/emscripten/system/include/libc
	-Xclang
	-isystem/path/to/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten
	-Xclang
	-isystem/path/to/emsdk/upstream/emscripten/system/local/include
	-Xclang
	-isystem/~/.emscripten_cache/wasm-obj/include
	-v
	-c
	-x c++
	-fvisibility-inlines-hidden
	-std=c++11
	-pthread
	-Os
	-Wall
	-fvisibility=hidden
	-Wno-inline
	-Wextra
	-Wno-long-long
	-Wno-unused-parameter
	-Wno-variadic-macros
	-Wunused-function
	-DBOOST_ALL_NO_LIB=1
	-DBOOST_THREAD_BUILD_LIB=1
	-DBOOST_THREAD_DONT_USE_CHRONO
	-DBOOST_THREAD_POSIX
	-DNDEBUG
	-I.
	-DEMSCRIPTEN
	-D__EMSCRIPTEN_PTHREADS__=1
	-pthread
	-pthread libs/thread/src/pthread/thread.cpp
	-fno-inline-functions
	-Xclang
	-isystem/path/to/emsdk/upstream/emscripten/system/include/SDL
	-c
	-o bin.v2/libs/thread/build/clang-linux-emscripten/release/link-static/optimization-space/threadapi-pthread/threading-multi/visibility-hidden/pthread/thread.o
	-mllvm
	-combiner-global-alias-analysis=false
	-mllvm
	-enable-emscripten-sjlj
	-mllvm
	-disable-lsr
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project fc19465965a74cffa41e385f3cfe9bfca6a7950d)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /path/to/emsdk/upstream/bin
```

**Comment by woodser** [comment]
Are you still unable to build from source?

**Comment by trasherdk** [comment]
Yes. No luck on that front.
And have no clue as to where to search for a solution. I've tried...
```
[ 11%] Linking CXX executable monero_core_wasm.js
wasm-ld: error: 'atomics' feature is used by thread.o, so --shared-memory must be used
wasm-ld: error: Target feature 'atomics' used in thread.o is disallowed by CMakeFiles/monero_core_wasm.dir/src/main/cpp/http_client_wasm.cpp.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in once.o is disallowed by CMakeFiles/monero_core_wasm.dir/src/main/cpp/http_client_wasm.cpp.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in future.o is disallowed by CMakeFiles/monero_core_wasm.dir/src/main/cpp/http_client_wasm.cpp.o. Use --no-check-features to suppress.
shared:ERROR: '/home/crypto/local/build/build-emscripten/emsdk/upstream/bin/wasm-ld @/tmp/emscripten_hk9M2R.rsp' failed (1)
CMakeFiles/monero_core_wasm.dir/build.make:1857: recipe for target 'monero_core_wasm.js' failed
gmake[2]: *** [monero_core_wasm.js] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/monero_core_wasm.dir/all' failed
gmake[1]: *** [CMakeFiles/monero_core_wasm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
gmake: *** [all] Error 2
```

**Comment by woodser** [comment]
Boost should not be building with pthreads, so that could very well be the problem.

I wonder if boost is installed elswhere on your system and that is where it's getting pthreads from?

**Comment by trasherdk** [comment]
Yes. Boost is installed default on Slackware.
```
/usr/lib64/libboost_atomic.a
/usr/lib64/libboost_chrono.a
/usr/lib64/libboost_container.a
/usr/lib64/libboost_context.a
/usr/lib64/libboost_coroutine.a
/usr/lib64/libboost_date_time.a
/usr/lib64/libboost_exception.a
/usr/lib64/libboost_filesystem.a
/usr/lib64/libboost_graph.a
/usr/lib64/libboost_iostreams.a
/usr/lib64/libboost_locale.a
/usr/lib64/libboost_log.a
/usr/lib64/libboost_log_setup.a
/usr/lib64/libboost_math_c99.a
/usr/lib64/libboost_math_c99f.a
/usr/lib64/libboost_math_c99l.a
/usr/lib64/libboost_math_tr1.a
/usr/lib64/libboost_math_tr1f.a
/usr/lib64/libboost_math_tr1l.a
/usr/lib64/libboost_prg_exec_monitor.a
/usr/lib64/libboost_program_options.a
/usr/lib64/libboost_python.a
/usr/lib64/libboost_random.a
/usr/lib64/libboost_regex.a
/usr/lib64/libboost_serialization.a
/usr/lib64/libboost_signals.a
/usr/lib64/libboost_system.a
/usr/lib64/libboost_test_exec_monitor.a
/usr/lib64/libboost_thread.a
/usr/lib64/libboost_timer.a
/usr/lib64/libboost_unit_test_framework.a
/usr/lib64/libboost_wave.a
/usr/lib64/libboost_wserialization.a
```
But shouldn't both `emsdk` and this thing be confined to their respective installed versions of `boost`?

**Comment by trasherdk** [comment]
I need a way to fix the Firefox problem, but can't find the node package that performs the actual fetch().
Searching `monero-javascript` yields few results:
```
$ search 'fetch('
Binary file ./node_modules/electron/dist/electron matches
Binary file ./node_modules/electron/dist/content_shell.pak matches
./node_modules/webpack/lib/web/FetchCompileWasmTemplatePlugin.js:20:                               `fetch(${mainTemplate.requireFn}.p + ${path})`;
./node_modules/form-data/README.md:219:fetch('http://example.com', { method: 'POST', body: form })
./node_modules/form-data/README.md.bak:219:fetch('http://example.com', { method: 'POST', body: form })
./node_modules/cacache/README.md:358:fetch(
./node_modules/cacache/README.es.md:353:fetch(
./node_modules/promise-throttle/README.md:78:      return fetch('example.com/a');
./node_modules/promise-throttle/README.md:81:      return fetch('example.com/b');
./node_modules/promise-throttle/README.md:99:  pt.add(function() { return fetch('example.com/a') });
./node_modules/promise-throttle/README.md:100:  pt.add(function() { return fetch('example.com/b') }, {signal: signal});
./node_modules/promise-throttle/README.md:101:  pt.add(function() { return fetch('example.com/c') });
./node_modules/promise-throttle/README.md:116:      return fetch('example.com/a');
./node_modules/promise-throttle/README.md:119:      return fetch('example.com/b');
```

**Comment by woodser** [comment]
Mind trying the latest master which is tagged for v0.3.0 release?

**Comment by trasherdk** [comment]
Just did a fresh build. Same error as before.
```
[ 59%] Linking CXX executable monero_core.js
wasm-ld: error: 'atomics' feature is used by thread.o, so --shared-memory must be used
em++: error: '/home/crypto/local/build/build-emscripten/emsdk/upstream/bin/wasm-ld @/tmp/emscripten_NzNRnd.rsp' failed (1)
CMakeFiles/monero_core.dir/build.make:1938: recipe for target 'monero_core.js' failed
gmake[2]: *** [monero_core.js] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/monero_core.dir/all' failed
gmake[1]: *** [CMakeFiles/monero_core.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
gmake: *** [all] Error 2
```

**Comment by woodser** [comment]
Hello there.  Mind trying this again with the latest release or master?  CMakeLists.txt in monero-javascript and monero-cpp now use system-installed dependencies.  It should hopefully resolve it.

**Comment by woodser** [comment]
This issue is fixed by specifying no pthreads in the [emscripten](https://github.com/monero-ecosystem/monero-javascript/blob/a8a6bcb854ae77e276c2ebd01771e510ea9d7bb2/configs/emscripten.jam#L13) and [boost](https://github.com/monero-ecosystem/monero-javascript/blob/a8a6bcb854ae77e276c2ebd01771e510ea9d7bb2/bin/build_boost_emscripten.sh#L114) configurations.

I've verified this fix to work on linux which was using pthreads as reported in this issue unless explicitly configured not to.

Please try it out and feel free to re-open this issue if you continue to have any problems.

Thanks for reporting and helping to debug.
