### ISSUE TITLE
I'm having issues understanding how to use this.

### ISSUE THREAD

**Issue by Spederan** [monero-ecosystem/monero-javascript#111]
I can't figure out how to use this library on the clientside. I will happily donate if someone can help me figure it out.  The instructions start off talking about using it on nodejs and webassembly, but all i want is to use it with vanilla javascript.

The first code snippet I see is this:

    const monerojs = require("monero-javascript");
    
    // connect to daemon
    let daemon = await monerojs.connectToDaemonRpc("http://localhost:38081", "superuser", "abctesting123");
    let height = await daemon.getHeight();            // 1523651
    let feeEstimate = await daemon.getFeeEstimate();  // 1014313512
    let txsInPool = await daemon.getTxPool();  

The problem is, ``require`` is only defined in NodeJS, and the next lines of code dont even make sense on their own, you cant use "await" without "async", and theres no async here. I feel theres a critical lack of context on whats going on here, and if this is even what im supposed to be using for the clientside or not.

Then I go over to Part 2 ( https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/getting_started_p2.md) and it's talking about nodejs and python being dependencies. What? What do those two things have to do with clientside javascript? The next thing i see is:

const monerojs = require("monero-javascript");

main();
async function main() {
  
  // create a random keys-only (offline) stagenet wallet
  let walletKeys = await monerojs.createWalletKeys({networkType: "stagenet", language: "English"});
  
  // print the wallet's attributes in the browser window
  document.getElementById("wallet_mnemonic_phrase").innerHTML = "Mnemonic phrase: " + await walletKeys.getMnemonic();
  document.getElementById("wallet_address").innerHTML = "Address: " + await walletKeys.getAddress(0, 0); // get address at account 0, subaddress 0
  document.getElementById("wallet_spend_key").innerHTML = "Spend key: " + await walletKeys.getPrivateSpendKey();
  document.getElementById("wallet_view_key").innerHTML = "View key: " + await walletKeys.getPrivateViewKey();
}

Which again, require is not defined in vanilla javascript.

So how do i use this in vanilla javascript only? Whats the simple explanation? Which exact files do i need? What line of code will run when i type them in?

I dont see any alternatives to this library so i cant proceed until I understand how to use this.

**Comment by Spederan** [comment]
I tried using browserify to make it usable by javascript, but it says it cannot walk the dependency graph. I am unsure what else to try at this point.

    browserify public/src/monero-javascript-master/index.js > monero-js-bundle.js
    Error: Can't walk dependency graph: Cannot find module 'promise-throttle' from '/home/anonymous/Documents/Spederan/speedrunjs/public/src/monero-javascript-master/src/main/js/common/HttpClient.js'
        required by /home/anonymous/Documents/Spederan/speedrunjs/public/src/monero-javascript-master/src/main/js/common/HttpClient.js
        at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:146:35
        at processDirs (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:299:39)
        at isdir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:306:32)
        at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:34:69
        at FSReqCallback.oncomplete (node:fs:207:21)
